In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("bug_prediction_raw_dataset.csv")
df

,repo,sha,parent_sha,parent_count,author_name,author_date,message,files_changed,additions,deletions,total_changes,is_fix_commit,buggy_label
0,tensorflow/tensorflow,6fdd92a19642ade16dac69238096ae02ccbaa11d,25821c1ae79073fbecab46b2ecb2f349d99140dc,1,Alexander Belyaev,2026-04-12T10:25:29Z,[XLA:GPU] Use a map from the parallel dim id t...,8,109,43,152,0,0
1,tensorflow/tensorflow,25821c1ae79073fbecab46b2ecb2f349d99140dc,f93564545e21173ea11f0a84537698ff65aa7474,1,A. Unique TensorFlower,2026-04-11T17:08:02Z,Reverts 7baf72cd5425d5f24c737f4379957eb0deb712...,1,1,1,2,0,0
2,tensorflow/tensorflow,f93564545e21173ea11f0a84537698ff65aa7474,701380fcf4daab3480586274885496d62c4627eb,1,A. Unique TensorFlower,2026-04-11T08:07:17Z,Automated Code Change PiperOrigin-RevId: 8980...,1,3,2,5,0,0
3,tensorflow/tensorflow,701380fcf4daab3480586274885496d62c4627eb,48156b4934dceff5c931fb19569b4093b8272b3c,1,A. Unique TensorFlower,2026-04-11T07:25:39Z,Automated Code Change PiperOrigin-RevId: 8980...,9,9,0,9,0,0
4,tensorflow/tensorflow,48156b4934dceff5c931fb19569b4093b8272b3c,2b976f75daf37a27af68982b35cb625854579d88,1,A. Unique TensorFlower,2026-04-11T06:42:17Z,Automated Code Change PiperOrigin-RevId: 8980...,1,1,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9980,deepset-ai/haystack,384c5edbbfe748d6ec98b45d755ad6fd68e2913c,f1f6f5b48ab205340fff0ed0f26e21d370a6667a,1,Stefano Fiorucci,2026-01-09T09:00:13Z,"ci: refine ""Release new minor version docs"" wo...",1,6,2,8,0,0
9981,deepset-ai/haystack,f1f6f5b48ab205340fff0ed0f26e21d370a6667a,605f13e84ee3d3bcad83665bd814d75e4bfd8efb,1,Haystack Bot,2026-01-08T14:29:11Z,Promote unstable docs for Haystack 2.22 (#10325),300,4,4,8,0,0
9982,deepset-ai/haystack,605f13e84ee3d3bcad83665bd814d75e4bfd8efb,cedad24a3ee115d2216847b6efa65798f038d885,1,Haystack Bot,2026-01-08T13:10:32Z,Sync Core Integrations API reference (opensear...,6,84,30,114,0,0
9983,deepset-ai/haystack,cedad24a3ee115d2216847b6efa65798f038d885,ec82faea96bdc60ec05cf2fc808508e690855589,1,Haystack Bot,2026-01-08T11:01:05Z,Sync Core Integrations API reference (amazon_b...,6,18,18,36,0,0
9984,deepset-ai/haystack,ec82faea96bdc60ec05cf2fc808508e690855589,19c85d2f3f947f09b554a5379f4aae458d8c3285,1,Haystack Bot,2026-01-08T10:52:52Z,Sync Core Integrations API reference (pinecone...,6,672,126,798,0,0

In [4]:
df = df.drop(['repo','sha','parent_sha','author_name','author_date'], axis=1)

In [5]:
df.isnull().sum()

parent_count     0
message          0
files_changed    0
additions        0
deletions        0
total_changes    0
is_fix_commit    0
buggy_label      0
dtype: int64

In [6]:
df['buggy_label'].value_counts()

buggy_label
0    5439
1    4546
Name: count, dtype: int64

In [7]:
df['buggy_label'].value_counts(normalize=True)

buggy_label
0    0.544717
1    0.455283
Name: proportion, dtype: float64

In [8]:
df.dtypes

parent_count      int64
message          object
files_changed     int64
additions         int64
deletions         int64
total_changes     int64
is_fix_commit     int64
buggy_label       int64
dtype: object

In [9]:
df.describe()

,parent_count,files_changed,additions,deletions,total_changes,is_fix_commit,buggy_label
count,9985.000000,9985.000000,9.985000e+03,9985.000000,9.985000e+03,9985.000000,9985.000000
mean,1.096144,7.499950,9.813349e+02,342.642364,1.323977e+03,0.474011,0.455283
std,0.294804,27.287624,2.796818e+04,9546.527784,2.993976e+04,0.499349,0.498021
min,1.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000
25%,1.000000,1.000000,5.000000e+00,1.000000,9.000000e+00,0.000000,0.000000
50%,1.000000,2.000000,2.600000e+01,6.000000,4.000000e+01,0.000000,0.000000
75%,1.000000,5.000000,1.160000e+02,29.000000,1.650000e+02,1.000000,1.000000
max,2.000000,300.000000,1.386698e+06,820147.000000,1.394819e+06,1.000000,1.000000

In [10]:
df.to_csv("bug_prediction_CLEAN_dataset.csv", index=False)
print("Saved: bug_prediction_CLEAN_dataset.csv")

Saved: bug_prediction_CLEAN_dataset.csv