In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("bug_prediction_raw_dataset_new.csv")
df

,repo,sha,parent_sha,parent_count,author_name,author_date,message,files_changed,additions,deletions,total_changes,message_length,commit_hour,commit_day,developer_experience,directories_changed,is_fix_commit,buggy_label
0,tensorflow/tensorflow,06ba7ec486ef88d1e496dd0dfe5a8d0663de3343,62011cf34d82e6d168b976eff033b0b78d3afbe5,1,Kanish Anand,2026-05-12T14:55:37Z,"Disable `HloShardingV3` in ShardyXLA tests, ad...",1,4,0,4,98,14,1,0,1,0,0
1,tensorflow/tensorflow,62011cf34d82e6d168b976eff033b0b78d3afbe5,0181888c80f3c17e4beb2a9e9189e90d61be38c9,1,Eetu Sjöblom,2026-05-12T13:57:34Z,PR #41616: [ROCm] Add PCIe and interconnect ba...,11,554,13,567,638,13,1,0,1,0,0
2,tensorflow/tensorflow,0181888c80f3c17e4beb2a9e9189e90d61be38c9,33643e996d4b98d282be0044afdabb984ee6cda4,1,Andrei Ivanov,2026-05-12T13:55:53Z,PR #42425: Add SM103 HLO op profiles for B300 ...,2,946,0,946,938,13,1,0,1,0,0
3,tensorflow/tensorflow,33643e996d4b98d282be0044afdabb984ee6cda4,ad8b78590b697e2812d1d374971b2fffecbca201,1,Adrian Kuegel,2026-05-12T13:52:29Z,[XLA:GPU] Migrate more tests away from GpuCode...,7,166,207,373,420,13,1,0,1,1,0
4,tensorflow/tensorflow,ad8b78590b697e2812d1d374971b2fffecbca201,47ae76a1b7eab2fde3424728e01b1f7d623d787c,1,Ahmed Sagar,2026-05-12T13:45:44Z,PR #35762: Fix permutation sort expander dtype...,2,52,1,53,2442,13,1,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,deepset-ai/haystack,ac9455dc8df2fba03653aaa124ac47f3a1e2dfe1,5b8c5338c198eca9453af71fbe1ec32e1912f339,1,Stefano Fiorucci,2026-02-09T08:38:00Z,docs: add section on flexible connections for ...,4,147,79,226,183,8,0,71,1,1,1
9995,deepset-ai/haystack,5b8c5338c198eca9453af71fbe1ec32e1912f339,5f89e9c9e75b5476f423f3e17c782b6cd6a9a320,1,alex li,2026-02-09T08:28:29Z,docs: remove stale Marqo document store links ...,15,12,49,61,54,8,0,0,2,0,1
9996,deepset-ai/haystack,5f89e9c9e75b5476f423f3e17c782b6cd6a9a320,f581edcabc8a2fb0fe7f755257784bc575ea55f9,1,Stefano Fiorucci,2026-02-06T15:46:09Z,feat: Pipelines - support connection and conve...,7,519,152,671,549,15,4,72,3,1,0
9997,deepset-ai/haystack,f581edcabc8a2fb0fe7f755257784bc575ea55f9,079bee49f04a925d7ce660a508c24e2b7d224d3a,1,dependabot[bot],2026-02-06T14:27:00Z,chore(deps): bump fossas/fossa-action from 1.7...,1,1,1,2,614,14,4,370,1,0,1
9998,deepset-ai/haystack,079bee49f04a925d7ce660a508c24e2b7d224d3a,d68f444667744d140a4f0ec8a34a06ae79b7de0a,1,Haystack Bot,2026-02-06T11:20:50Z,Sync Haystack API reference on Docusaurus (#10...,1,13,11,24,113,11,4,176,1,0,0

In [3]:
df = df.drop(['repo','sha','parent_sha','author_name','author_date', 'message', 'is_fix_commit'], axis=1)

In [4]:
df.isnull().sum()

parent_count            0
files_changed           0
additions               0
deletions               0
total_changes           0
message_length          0
commit_hour             0
commit_day              0
developer_experience    0
directories_changed     0
buggy_label             0
dtype: int64

In [5]:
df['buggy_label'].value_counts()

buggy_label
0    5355
1    4644
Name: count, dtype: int64

In [6]:
df['buggy_label'].value_counts(normalize=True)

buggy_label
0    0.535554
1    0.464446
Name: proportion, dtype: float64

In [7]:
df.dtypes

parent_count            int64
files_changed           int64
additions               int64
deletions               int64
total_changes           int64
message_length          int64
commit_hour             int64
commit_day              int64
developer_experience    int64
directories_changed     int64
buggy_label             int64
dtype: object

In [8]:
df.describe()

,parent_count,files_changed,additions,deletions,total_changes,message_length,commit_hour,commit_day,developer_experience,directories_changed,buggy_label
count,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000
mean,1.086709,7.627263,643.984498,512.165517,1156.150015,653.218622,12.779778,2.527553,48.814181,1.310931,0.464446
std,0.281422,27.354569,9096.108974,15205.111770,19201.953905,1841.982954,6.442003,1.791384,74.519386,0.834009,0.498759
min,1.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,1.000000,5.000000,1.000000,10.000000,66.000000,8.000000,1.000000,2.000000,1.000000,0.000000
50%,1.000000,2.000000,29.000000,5.000000,43.000000,130.000000,14.000000,3.000000,15.000000,1.000000,0.000000
75%,1.000000,5.000000,127.000000,26.000000,176.000000,509.000000,18.000000,4.000000,62.000000,1.000000,1.000000
max,2.000000,300.000000,533455.000000,836637.000000,954066.000000,65260.000000,23.000000,6.000000,395.000000,18.000000,1.000000

In [9]:
df.to_csv("CLEAN_dataset.csv", index=False)
print("Saved: CLEAN_dataset.csv")

Saved: CLEAN_dataset.csv

# **Modeling**

In [ ]:

X = df.drop("buggy_label", axis=1)
y = df["buggy_label"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)